language: node_js
node_js:
    - "11"
    - "10"
    - "9"

addons:
  sonarcloud:
    organization: "unknownskl-github"

script:
  - npm test
  - sonar-scanner

before_install:
  - sudo apt-get -y install python2-pip python-dev
  - sudo pip3 install -U setuptools
  - sudo pip3 install -U virtualenvwrapper
  - python -V
